### PR TITLE
fix: add index.d.ts (TypeScript support)

### LINKED ISSUE #8: Typescript definition
currently importing like
`import kebabCase from 'kebab-case'`

throws a typescript error
> Could not find a declaration file for module 'kebab-case'. 'C:/DEVELOPMENT/xxx/node_modules/.pnpm/kebab-case@1.0.1/node_modules/kebab-case/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/kebab-case` if it exists or add a new declaration (.d.ts) file containing `declare module 'kebab-case';`

also, the @types/kebab-case still does not exist

### PR DESCRIPTION
**Pull request by gomes042**
fix #8

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+type fn = (str: string) => string;
+
+interface kebabCase extends fn {
+    reverse: fn
+}
+
+const kebabCase: kebabCase;
+
+export default kebabCase;
```
Comment (joakimbeng) [inline index.d.ts]: IMO types should be PascalCased/UpperCamelCased, i.e. I suggest changing this to:
```suggestion
type Fn = (str: string) => string;

interface KebabCase extends Fn {
    reverse: Fn
}

const kebabCase: KebabCase;

export default kebabCase;
```

**Review by joakimbeng — APPROVED** [review]
